Repository eosnetworkfoundation/mandel, pull requests merged in 2022-08, with the labels that each got.

#736 [3.2] Update, Replace, and Check Validity of WASM files in mandel
  unittests/api_tests.cpp
  unittests/protocol_feature_tests.cpp
  unittests/test-contracts/action_results/action_results.wasm
  unittests/test-contracts/asserter/asserter.abi
  unittests/test-contracts/asserter/asserter.wasm
  unittests/test-contracts/crypto_primitives_test/crypto_primitives_test.abi
  unittests/test-contracts/crypto_primitives_test/crypto_primitives_test.wasm
  unittests/test-contracts/deferred_test/deferred_test.abi
  unittests/test-contracts/deferred_test/deferred_test.wasm
  unittests/test-contracts/get_block_num_test/get_block_num_test.abi
  unittests/test-contracts/get_block_num_test/get_block_num_test.wasm
  unittests/test-contracts/get_sender_test/get_sender_test.abi
  unittests/test-contracts/get_sender_test/get_sender_test.wasm
  unittests/test-contracts/get_table_seckey_test/get_table_seckey_test.abi
  unittests/test-contracts/get_table_seckey_test/get_table_seckey_test.wasm
  unittests/test-contracts/get_table_test/get_table_test.wasm
  unittests/test-contracts/integration_test/integration_test.abi
  unittests/test-contracts/integration_test/integration_test.wasm
  unittests/test-contracts/noop/noop.abi
  unittests/test-contracts/noop/noop.wasm
  unittests/test-contracts/params_test/params_test.wasm
  unittests/test-contracts/payloadless/payloadless.abi
  unittests/test-contracts/payloadless/payloadless.wasm
  unittests/test-contracts/proxy/proxy.abi
  unittests/test-contracts/proxy/proxy.wasm
  unittests/test-contracts/ram_restrictions_test/ram_restrictions_test.abi
  unittests/test-contracts/ram_restrictions_test/ram_restrictions_test.wasm
  unittests/test-contracts/reject_all/reject_all.wasm
  unittests/test-contracts/restrict_action_test/restrict_action_test.abi
  unittests/test-contracts/restrict_action_test/restrict_action_test.wasm
  unittests/test-contracts/snapshot_test/snapshot_test.abi
  unittests/test-contracts/snapshot_test/snapshot_test.wasm
  unittests/test-contracts/test_api/test_api.wasm
  unittests/test-contracts/test_api_db/test_api_db.abi
  unittests/test-contracts/test_api_db/test_api_db.wasm
  unittests/test-contracts/test_api_multi_index/test_api_multi_index.abi
  unittests/test-contracts/test_api_multi_index/test_api_multi_index.wasm
  unittests/test-contracts/wasm_config_bios/wasm_config_bios.abi
  unittests/test-contracts/wasm_config_bios/wasm_config_bios.wasm
  unittests/whitelist_blacklist_tests.cpp
Labels: 3.2 Candidate, OCI

#734 Backport cleos optional support
  libraries/chain/abi_serializer.cpp
  libraries/testing/contracts.hpp.in
  tests/CMakeLists.txt
  tests/nested_container_multi_index_test.py
  unittests/abi_tests.cpp
  unittests/test-contracts/CMakeLists.txt
  unittests/test-contracts/nested_container_multi_index/CMakeLists.txt
  unittests/test-contracts/nested_container_multi_index/nested_container_multi_index.abi
  unittests/test-contracts/nested_container_multi_index/nested_container_multi_index.cpp
  unittests/test-contracts/nested_container_multi_index/nested_container_multi_index.wasm
Labels: OCI

#757 [3.1 -> main] Attempt connection retries for duplicate connections
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#791 [3.1] Reduce net_plugin handshake messages in case of unavailable blocks
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#798 [3.1 -> main] Reduce net_plugin handshake messages in case of unavailable blocks
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#753 [3.2] insert comments in the kv_config header file indicating it is not in use
  libraries/chain/include/eosio/chain/kv_config.hpp
Labels: 3.2 Candidate, OCI

#750 [3.2] move trace api plugin activation out of tests and into cluster
  tests/Cluster.py
  tests/block_log_retain_blocks_test.py
  tests/block_log_util_test.py
  tests/compute_transaction_test.py
  tests/distributed-transactions-test.py
  tests/get_account_test.py
  tests/large-lib-test.py
  tests/launcher_test.py
  tests/light_validation_sync_test.py
  tests/nested_container_multi_index_test.py
  tests/nodeos_chainbase_allocation_test.py
  tests/nodeos_contrl_c_test.py
  tests/nodeos_extra_packed_data_test.py
  tests/nodeos_forked_chain_test.py
  tests/nodeos_high_transaction_test.py
  tests/nodeos_irreversible_mode_test.py
  tests/nodeos_multiple_version_protocol_feature_test.py
  tests/nodeos_producer_watermark_test.py
  tests/nodeos_read_terminate_at_block_test.py
  tests/nodeos_retry_transaction_test.py
  tests/nodeos_run_remote_test.py
  tests/nodeos_run_test.py
  tests/nodeos_short_fork_take_over_test.py
  tests/nodeos_startup_catchup.py
  tests/nodeos_under_min_avail_ram.py
  tests/nodeos_voting_test.py
  tests/p2p_high_latency_test.py
  tests/prod_preactivation_test.py
  tests/restart-scenarios-test.py
  tests/ship_streamer_test.py
  tests/ship_test.py
  tests/subjective_billing_test.py
  tests/terminate-scenarios-test.py
  tests/trace_plugin_test.py
  tests/trx_finality_status_forked_test.py
  tests/trx_finality_status_test.py
Labels: 3.2 Candidate, OCI

#748 documentation fixes to power developer doc portal
  docs/00_install/01_build-from-source/00_build-unsupported-os.md
  docs/00_install/01_build-from-source/index.md
  docs/01_nodeos/02_usage/03_development-environment/index.md
  docs/01_nodeos/03_plugins/history_api_plugin/index.md
  docs/01_nodeos/03_plugins/net_api_plugin/index.md
  docs/01_nodeos/03_plugins/net_plugin/index.md
  docs/01_nodeos/03_plugins/state_history_plugin/10_how-to-fast-start-without-old-history.md
  docs/01_nodeos/03_plugins/state_history_plugin/40_how-to-restore-snapshot-with-full-history.md
  docs/01_nodeos/07_concepts/05_storage-and-read-modes.md
  docs/01_nodeos/08_troubleshooting/index.md
  docs/02_cleos/02_how-to-guides/how-to-create-a-wallet.md
  docs/02_cleos/02_how-to-guides/how-to-create-an-account.md
  docs/02_cleos/02_how-to-guides/how-to-delegate-CPU-resource.md
  docs/02_cleos/02_how-to-guides/how-to-delegate-net-resource.md
  docs/02_cleos/02_how-to-guides/how-to-get-account-information.md
  docs/02_cleos/02_how-to-guides/how-to-get-block-information.md
  docs/02_cleos/02_how-to-guides/how-to-get-transaction-information.md
  docs/02_cleos/02_how-to-guides/how-to-import-a-key.md
  docs/02_cleos/02_how-to-guides/how-to-list-all-key-pairs.md
  docs/02_cleos/03_command-reference/get/account.md
  docs/02_cleos/03_command-reference/net/peers.md
  docs/02_cleos/03_command-reference/net/status.md
  docs/02_cleos/03_command-reference/set/set-account.md
  docs/02_cleos/03_command-reference/set/set-action.md
  docs/index.md
  tutorials/bios-boot-tutorial/README.md
Labels: documentation
