Repository eosnetworkfoundation/mandel, pull requests merged in 2022-05, with the labels that each got.

#230 Increase http-max-response-time-ms for tests
  tests/trx_finality_status_forked_test.py
  tests/trx_finality_status_test.py
Labels: OCI

#226 Transaction logging fix
  libraries/chain/abi_serializer.cpp
  plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
  plugins/producer_plugin/producer_plugin.cpp
  plugins/txn_test_gen_plugin/txn_test_gen_plugin.cpp
  programs/nodeos/logging.json
Labels: OCI

#223 Backported code to preemptively create wallet dir
  plugins/wallet_plugin/wallet_plugin.cpp
  programs/keosd/main.cpp
Labels: OCI

#233 cleaned up handling of failed startup from snapshot
  libraries/chain/controller.cpp
Labels: OCI

#169 Backport eosio/eos 2.1 version of net_plugin
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#156 net_plugin call accept_transaction on net thread
  plugins/net_plugin/net_plugin.cpp
  plugins/producer_plugin/producer_plugin.cpp
Labels: OCI

#250 Fix test_trx_finality_status_processing test
  plugins/chain_plugin/test/test_trx_finality_status_processing.cpp
Labels: OCI

#255 Backport fix for push_block
  plugins/chain_plugin/chain_plugin.cpp
Labels: OCI

#267 Backport: Reduce logging for failed http plugin calls
  plugins/http_plugin/http_plugin.cpp
Labels: OCI

#268 trace history log messages should print nicely in syslog
  libraries/state_history/include/eosio/state_history/log.hpp
Labels: OCI

#270 Remove unnecessary strlen
  libraries/chain/include/eosio/chain/webassembly/common.hpp
Labels: OCI

#271 Apply 400 check to db_size
  plugins/db_size_api_plugin/db_size_api_plugin.cpp
  tests/plugin_http_api_test.py
Labels: OCI

#272 Default to returning WASM as returning WAST has been deprecated.
  plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
Labels: OCI

#273 Fix duplicate symbol error in trace_api::configuration_utils
  plugins/trace_api_plugin/CMakeLists.txt
  plugins/trace_api_plugin/configuration_utils.cpp
  plugins/trace_api_plugin/include/eosio/trace_api/configuration_utils.hpp
Labels: OCI

#266 Backport: chain api plugin / get_activated_protocol_features modifications
  plugins/chain_api_plugin/chain.swagger.yaml
  plugins/chain_plugin/chain_plugin.cpp
  tests/plugin_http_api_test.py
Labels: OCI

#275 cleos remove wasm to wast conversion
  libraries/chain/include/eosio/chain/wast_to_wasm.hpp
  libraries/chain/wast_to_wasm.cpp
  programs/cleos/main.cpp
  unittests/wasm_tests.cpp
Labels: OCI

#278 Added earliest available block to get_info
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/controller.hpp
  plugins/chain_plugin/chain_plugin.cpp
  plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
Labels: OCI

#283 Fix all python tests to correctly report failure exit code on failure including any exception thrown.
  tests/block_log_util_test.py
  tests/compute_transaction_test.py
  tests/distributed-transactions-remote-test.py
  tests/distributed-transactions-test.py
  tests/http_plugin_test.py
  tests/launcher_test.py
  tests/nodeos_forked_chain_test.py
  tests/nodeos_producer_watermark_test.py
  tests/nodeos_run_remote_test.py
  tests/nodeos_run_test.py
  tests/nodeos_short_fork_take_over_test.py
  tests/nodeos_startup_catchup.py
  tests/nodeos_under_min_avail_ram.py
  tests/nodeos_voting_test.py
  tests/p2p_high_latency_test.py
  tests/p2p_network_test.py
  tests/prod_preactivation_test.py
  tests/restart-scenarios-test.py
  tests/subjective_billing_test.py
  tests/terminate-scenarios-test.py
  tests/trx_finality_status_forked_test.py
  tests/trx_finality_status_test.py
  tests/validate-dirty-db.py
Labels: OCI

#281 Add integration test for nodeos shutdown
  tests/CMakeLists.txt
  tests/nodeos_contrl_c_test.py
Labels: OCI

#287 Fix test error log statement and import
  tests/nodeos_forked_chain_test.py
Labels: 3.1 Candidates, OCI

#298 Apply 3-strike rule for complete block production - 2.0
  plugins/producer_plugin/producer_plugin.cpp
Labels: OCI

#307 Updated CMakeLists.txt/README.md for version 2.0.14
  CMakeLists.txt
  README.md
Labels: OCI

#311 Backported exit on fork_db corrupted
  libraries/chain/controller.cpp
  plugins/producer_plugin/producer_plugin.cpp
Labels: OCI

#312 Backport of unpacking packed transaction in cleos
  programs/cleos/main.cpp
  tests/cli_test.py
Labels: OCI

#308 Explicit Values for builtin_protocol_feature_t enum
  libraries/chain/include/eosio/chain/protocol_feature_manager.hpp
  unittests/deep-mind/deep-mind.log
Labels: CONSENSUS, OCI

#313 Bump up successful trx cache expiration to 60s in integration test.
  tests/trx_finality_status_test.py
Labels: OCI

#299 Apply 3-strike rule for complete block production
  plugins/producer_plugin/producer_plugin.cpp
Labels: OCI

#302 Add linked permissions to get_account
  plugins/chain_plugin/chain_plugin.cpp
  plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
  programs/cleos/main.cpp
  tests/CMakeLists.txt
  tests/chain_plugin_tests.cpp
  tests/get_account_test.py
Labels: OCI

#329 Add hash verification to get_activated_protocol_features test
  tests/plugin_http_api_test.py
Labels: OCI
