Repository eosnetworkfoundation/mandel, pull requests merged in 2022-06, with the labels that each got.

#338 trace_api_plugin eosio/eos 2.1 compatibility
  plugins/trace_api_plugin/include/eosio/trace_api/chain_extraction.hpp
  plugins/trace_api_plugin/include/eosio/trace_api/trace.hpp
Labels: OCI

#347 Modified parameter to compute_transaction
  plugins/chain_plugin/chain_plugin.cpp
  plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
  programs/cleos/main.cpp
Labels: OCI

#350 Bump snapshot version to v6
  libraries/chain/include/eosio/chain/chain_snapshot.hpp
  unittests/snapshot_tests.cpp
  unittests/snapshots/CMakeLists.txt
  unittests/snapshots/snap_v6.bin.gz
  unittests/snapshots/snap_v6.json.gz
Labels: OCI

#377 Suppress "End of file" error reporting in SHiP
  plugins/state_history_plugin/state_history_plugin.cpp
Labels: 3.1 Candidates, OCI

#378 use sh instead of bash for cmake unittests
  unittests/CMakeLists.txt
Labels: 3.1 Candidates, OCI

#385 Fix clang compiler error
  libraries/chain/deep_mind.cpp
Labels: OCI

#389 Boost.Test to report the last checkpoint location
  libraries/testing/include/eosio/testing/tester.hpp
  unittests/main.cpp
Labels: 3.2 Candidate, OCI

#387 plugin_http_api_test - fix timing issue
  tests/Node.py
Labels: OCI, 3.1 RC2

#381 net_plugin delay connecting to peers
  plugins/net_plugin/net_plugin.cpp
Labels: OCI, 3.1 RC2

#409 Fix plugin http api test [main]
  tests/Node.py
Labels: OCI

#480 Remove confusing error message - 3.1
  programs/cleos/main.cpp
Labels: OCI

#486 Remove confusing error message - main
  programs/cleos/main.cpp
Labels: OCI

#472 Fix issue with current block not sent to SHiP clients - 3.1
  plugins/state_history_plugin/state_history_plugin.cpp
  tests/CMakeLists.txt
  tests/ship_streamer.cpp
  tests/ship_streamer_test.py
  tests/ship_test.py
Labels: OCI

#494 Fix issue with current block not sent to SHiP clients - main
  plugins/state_history_plugin/state_history_plugin.cpp
  scripts/pinned_build.sh
  tests/CMakeLists.txt
  tests/ship_streamer.cpp
  tests/ship_streamer_test.py
  tests/ship_test.py
Labels: OCI

#411 Make /v1/chain/get_accounts_by_authorizers multi-threaded
  plugins/chain_api_plugin/chain_api_plugin.cpp
  plugins/chain_plugin/test/test_account_query_db.cpp
  plugins/http_plugin/include/eosio/http_plugin/http_plugin.hpp
Labels: OCI

#489 Eliminate use of boost deprecated query object.
  plugins/http_plugin/http_plugin.cpp
Labels: 3.2 Candidate, OCI

#491 Using get raw abi in cleos
  programs/cleos/main.cpp
Labels: 3.2 Candidate, OCI

#492 Replace hard coding system_account_name
  programs/cleos/main.cpp
Labels: 3.2 Candidate, OCI

#495 Backport: Send handshake for heartbeat/2 if no block -- main
  plugins/net_plugin/net_plugin.cpp
Labels: 3.2 Candidate

#500 Backport of the cleos validate signatures
  programs/cleos/main.cpp
Labels: OCI

#493 Add additional CPU/NET usage data to get_account results
  libraries/chain/include/eosio/chain/resource_limits.hpp
  libraries/chain/resource_limits.cpp
  plugins/chain_plugin/chain_plugin.cpp
  plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
  programs/cleos/main.cpp
  unittests/resource_limits_test.cpp
Labels: 3.2 Candidate, OCI

#509 Backport: two comment fixes to transaction.hpp
  libraries/chain/include/eosio/chain/transaction.hpp
Labels: OCI

#502 fix libff in 3.1 tester cmakes
  CMakeLists.txt
  CMakeModules/EosioTesterBuild.cmake.in
Labels: OCI

#510 [3.2] Add a second account and action to test_exhaustive_snapshot
  unittests/snapshot_tests.cpp
Labels: 3.2 Candidate

#539 [3.1] Fix log trimming of hex_data JSON output.
  libraries/chain/include/eosio/chain/abi_serializer.hpp
  programs/eosio-launcher/main.cpp
Labels: OCI

#541 [3.2] Separate out signature provider from producer plugin
  plugins/CMakeLists.txt
  plugins/producer_plugin/CMakeLists.txt
  plugins/producer_plugin/include/eosio/producer_plugin/producer_plugin.hpp
  plugins/producer_plugin/producer_plugin.cpp
  plugins/signature_provider_plugin/CMakeLists.txt
  plugins/signature_provider_plugin/include/eosio/signature_provider_plugin/signature_provider_plugin.hpp
  plugins/signature_provider_plugin/signature_provider_plugin.cpp
Labels: OCI

#549 [3.2] Fix log trimming of hex_data JSON output.
  libraries/chain/include/eosio/chain/abi_serializer.hpp
  programs/eosio-launcher/main.cpp
Labels: OCI

#543 [3.2] Add authority structure to cleos system newaccount
  programs/cleos/main.cpp
  tests/Node.py
  tests/nodeos_run_test.py
Labels: 3.2 Candidate, OCI

#537 [3.2] Additional transaction/block time logging
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/controller.hpp
  libraries/testing/include/eosio/testing/tester.hpp
  libraries/testing/tester.cpp
  plugins/producer_plugin/producer_plugin.cpp
  unittests/block_tests.cpp
  unittests/forked_tests.cpp
Labels: OCI

#547 [3.2] Backport cleos transaction signature keys
  programs/cleos/main.cpp
  tests/Cluster.py
  tests/Node.py
  tests/nodeos_run_test.py
  tests/nodeos_under_min_avail_ram.py
  tests/p2p_network_test.py
  tests/plugin_http_api_test.py
  tests/prod_preactivation_test.py
Labels: 3.2 Candidate, OCI

#551 [3.2] skip context free actions during light validation
  libraries/chain/apply_context.cpp
  libraries/chain/transaction_context.cpp
  unittests/api_tests.cpp
Labels: 3.2 Candidate, OCI
