Repository eosnetworkfoundation/mandel, pull requests merged in 2022-07, with the labels that each got.

#580 [3.2] Backport unpack transaction data
  programs/cleos/main.cpp
  tests/Node.py
  tests/nodeos_run_test.py
Labels: 3.2 Candidate, OCI

#581 [3.2] Backport: Fix unpack data for signing transaction
  programs/cleos/main.cpp
  tests/Node.py
  tests/nodeos_run_test.py
  tests/testUtils.py
Labels: 3.2 Candidate, OCI

#584 [3.2] Backport: Add trace plugin API test
  tests/CMakeLists.txt
  tests/Node.py
  tests/trace_plugin_test.py
Labels: 3.2 Candidate, OCI

#573 [3.2] Add block replay test
  libraries/testing/include/eosio/testing/tester.hpp
  libraries/testing/tester.cpp
  unittests/restart_chain_tests.cpp
Labels: 3.2 Candidate, OCI

#582 [3.2] Add light validation sync test
  tests/CMakeLists.txt
  tests/light_validation_sync_test.py
Labels: 3.2 Candidate, OCI

#587 Github workflow to create new jira issues on OCI label
  .github/workflows/jiraIssueCreator.yml
Labels: OCI

#591 [3.1] Fix race condition on trace_api_plugin shutdown
  plugins/trace_api_plugin/include/eosio/trace_api/store_provider.hpp
  plugins/trace_api_plugin/store_provider.cpp
Labels: OCI, 3.1 RC2

#566 [3.1] fixup CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 3.1 RC2

#550 [3.2] Add logs to artifacts
  .github/workflows/ubuntu-2004.yml
Labels: OCI

#592 [3.1] Fix race condition on trace_api_plugin shutdown
  plugins/trace_api_plugin/include/eosio/trace_api/store_provider.hpp
  plugins/trace_api_plugin/store_provider.cpp
Labels: OCI, 3.1 RC2

#603 [3.2] Update jiraIssueCreator.yml
  .github/workflows/jiraIssueCreator.yml
Labels: OCI

#596 [3.1] various README.md improvements w.r.t. build & branches
  README.md
Labels: 3.1 RC2

#625 Backport SHiP tests
  unittests/CMakeLists.txt
  unittests/state_history_tests.cpp
Labels: OCI

#622 [3.2] Backport test contract fixes
  unittests/CMakeLists.txt
  unittests/test-contracts/CMakeLists.txt
  unittests/test-contracts/get_sender_test/get_sender_test.hpp
  unittests/test-contracts/test_api/test_action.cpp
  unittests/test-contracts/test_api/test_api.cpp
  unittests/test-contracts/test_api/test_api.hpp
  unittests/test-contracts/test_api/test_api_common.hpp
  unittests/test-contracts/test_api/test_chain.cpp
  unittests/test-contracts/test_api/test_checktime.cpp
  unittests/test-contracts/test_api/test_crypto.cpp
  unittests/test-contracts/test_api/test_datastream.cpp
  unittests/test-contracts/test_api/test_permission.cpp
  unittests/test-contracts/test_api/test_print.cpp
  unittests/test-contracts/test_api/test_transaction.cpp
  unittests/test-contracts/test_api/test_types.cpp
  unittests/test-contracts/wasm_config_bios/wasm_config_bios.cpp
Labels: 3.2 Candidate, OCI

#627 [3.1] Fix for block producer stuck in coma state
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#629 [3.1 -> main] Fix for block producer stuck in coma state
  plugins/net_plugin/net_plugin.cpp
Labels: OCI

#628 [3.2] Add snapshot test and refactor pending_snapshot
  plugins/producer_plugin/CMakeLists.txt
  plugins/producer_plugin/include/eosio/producer_plugin/pending_snapshot.hpp
  plugins/producer_plugin/pending_snapshot.cpp
  plugins/producer_plugin/producer_plugin.cpp
  plugins/producer_plugin/test/CMakeLists.txt
  plugins/producer_plugin/test/test_snapshot_information.cpp
Labels: OCI

#630 [3.2] Allow HTTP-RPC with empty response
  plugins/http_plugin/http_plugin.cpp
  plugins/http_plugin/include/eosio/http_plugin/http_plugin.hpp
Labels: OCI

#634 [3.2] Backport of 2.1 optimizations
  libraries/chain/block_log.cpp
  libraries/chain/controller.cpp
  libraries/chain/include/eosio/chain/block_log.hpp
  libraries/chain/include/eosio/chain/types.hpp
  tests/block_log.cpp
  unittests/block_log_extract.cpp
Labels: OCI

#644 [3.2] Backport: pop a delta with empty rows
  libraries/state_history/create_deltas.cpp
  unittests/state_history_tests.cpp
Labels: OCI

#661 [3.2] Backport: Add unit tests for new fields get account in chain_plugin
  plugins/chain_plugin/test/CMakeLists.txt
  plugins/chain_plugin/test/test_chain_plugin.cpp
Labels: OCI

#650 [3.2] force the plugin_http_api_test to use a custom config dir
  tests/plugin_http_api_test.py
Labels: OCI

#667 [3.2] Backport: fix wrong cleos version returned in getClientVersion of tests/Cluster.py
  tests/Cluster.py
Labels: OCI

#654 [3.1] Use signed transaction for PUSH_CREATE action deep-mind logging.
  libraries/chain/deep_mind.cpp
  libraries/chain/include/eosio/chain/deep_mind.hpp
  libraries/chain/transaction_context.cpp
Labels: OCI

#652 [3.2] extra transaction data integration test
  tests/CMakeLists.txt
  tests/nodeos_extra_packed_data_test.py
Labels: OCI

#684 [3.1 -> main] Fix trx_finality_status_test
  tests/trx_finality_status_test.py
Labels: OCI

#686 [3.2] Merge pull request #10727 from EOSIO/keke_epe948
  libraries/chain/abi_serializer.cpp
  libraries/chain/include/eosio/chain/abi_serializer.hpp
Labels: OCI

#688 [3.2] Add tests for creating public key with no private key
  unittests/auth_tests.cpp
  unittests/misc_tests.cpp
Labels: 3.2 Candidate, OCI

#695 [3.2] Backported SHiP transaction extension unit test
  unittests/state_history_tests.cpp
Labels: OCI

#692 [3.2] Add chain api get_consensus_parameters
  plugins/chain_api_plugin/chain_api_plugin.cpp
  plugins/chain_plugin/chain_plugin.cpp
  plugins/chain_plugin/include/eosio/chain_plugin/chain_plugin.hpp
  plugins/net_api_plugin/net_api_plugin.cpp
  programs/cleos/httpc.hpp
  programs/cleos/main.cpp
Labels: 3.2 Candidate, OCI

#701 [3.2] Backport action serialization to always include hex_data.
  libraries/chain/include/eosio/chain/abi_serializer.hpp
  unittests/abi_tests.cpp
Labels: OCI

#709 [3.2] Add test cases for get_consensus_parameters RPC endpoint
  tests/chain_plugin_tests.cpp
  tests/plugin_http_api_test.py
Labels: 3.2 Candidate, OCI

#340 [3.2] Backporting state history plugin improvements and fixes
  libraries/state_history/create_deltas.cpp
  libraries/state_history/include/eosio/state_history/log.hpp
  plugins/state_history_plugin/state_history_plugin.cpp
  tests/CMakeLists.txt
  tests/ship_client.cpp
  tests/ship_test.py
Labels: 3.2 Candidate
